# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: sphinx-multiversion-jb
author: Henrik Finsberg
logo: "_static/logo.png"
copyright: "2025"
only_build_toc_files: true

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: cache
  timeout: 3000

# Information about where the book exists on the web
repository:
  url: https://github.com/finsberg/sphinx-multiversion-jb # Online location of your book
  branch: main


html:
  use_issues_button: true
  use_repository_button: true

parse:
  myst_enable_extensions:
    - amsmath
    - dollarmath
    - linkify

sphinx:
  config:
    html_last_updated_fmt: "%b %d, %Y"
    html_static_path: ["_static"]
    html_theme_options:
      primary_sidebar_end: ["version-switcher"]
      switcher:
        json_url: "https://raw.githubusercontent.com/finsberg/sphinx-docs-multiversions-jb/refs/heads/main/_static/version_switcher.json"
        version_match: "0.2.0"
      show_version_warning_banner: True
    # bibtex_bibfiles: ["docs/refs.bib"]
    nb_execution_show_tb: True
    nb_custom_formats:  # https://jupyterbook.org/en/stable/file-types/jupytext.html#file-types-custom
        .py:
            - jupytext.reads
            - fmt: py

    suppress_warnings: ["mystnb.unknown_mime_type", "bibtex.duplicate_citation"]
    codeautolink_concat_default: True
    intersphinx_mapping:
      basix : ["https://docs.fenicsproject.org/basix/main/python/", null]
      ffcx : ["https://docs.fenicsproject.org/ffcx/main/", null]
      ufl : ["https://docs.fenicsproject.org/ufl/main/", null]
      dolfinx : ["https://docs.fenicsproject.org/dolfinx/main/python", null]
      petsc4py: ["https://petsc.org/release/petsc4py", null]
      mpi4py: ["https://mpi4py.readthedocs.io/en/stable", null]
      numpy: ["https://numpy.org/doc/stable/", null]
      matplotlib: ["https://matplotlib.org/stable/", null]
      pyvista: ["https://docs.pyvista.org/", null]
      packaging: ["https://packaging.pypa.io/en/stable/", null]


  extra_extensions:
  - 'sphinx.ext.autodoc'
  - 'sphinx.ext.napoleon'
  - 'sphinx.ext.viewcode'
  - 'sphinx_copybutton'
  - 'sphinx_codeautolink'
  - 'sphinx.ext.intersphinx'

exclude_patterns: [".pytest_cache/*", ".github/*", ".tox/*", "third_party/*"]